// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJAXi_RJNLwPEKjKjHlNeMlX4UCpTM-GU',
    appId: '1:271591303190:web:78b1015d6fb432573aad37',
    messagingSenderId: '271591303190',
    projectId: 'flutter-test-221147',
    authDomain: 'flutter-test-221147.firebaseapp.com',
    storageBucket: 'flutter-test-221147.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTuxWEgvARGgA-CrzenoyrRVULm2SOc3g',
    appId: '1:271591303190:android:8e4424359341275c3aad37',
    messagingSenderId: '271591303190',
    projectId: 'flutter-test-221147',
    storageBucket: 'flutter-test-221147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQbLvWs5MNhHWVTnnkUF22ul0sHyiOQE',
    appId: '1:271591303190:ios:33134d0874f59f0d3aad37',
    messagingSenderId: '271591303190',
    projectId: 'flutter-test-221147',
    storageBucket: 'flutter-test-221147.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestProject',
  );
}
